In [1]:
import pandas as pd
import numpy as np

In [2]:
commercial = pd.read_excel('Two_wheeler_Raw.xlsx')

In [3]:
cibil = pd.read_excel('Two_wheeler_Cibil_Score.xlsx')

In [6]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_DOB', 'cus_MartialTypeId',
       'cus_Dependants', 'cus_CurrenResTypeId', 'cus_CurrenStyYear',
       'app_CustBankClosBal', 'app_CustAssetValue', 'app_CustProductCatTypeId',
       'app_CustBrandTypeId', 'app_CustIndustryTypeId', 'app_CustTenure',
       'app_CustInstalCount', 'app_CustChasAsset', 'app_CustChasInitial',
       'app_CustChasFinance', 'app_CustFinanInterest', 'app_CustEMI',
       'app_CustTotInflow', 'Label'],
      dtype='object')

In [7]:
commercial["Score"] = np.nan
commercial["AnotherScore"] = np.nan

In [8]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_DOB', 'cus_MartialTypeId',
       'cus_Dependants', 'cus_CurrenResTypeId', 'cus_CurrenStyYear',
       'app_CustBankClosBal', 'app_CustAssetValue', 'app_CustProductCatTypeId',
       'app_CustBrandTypeId', 'app_CustIndustryTypeId', 'app_CustTenure',
       'app_CustInstalCount', 'app_CustChasAsset', 'app_CustChasInitial',
       'app_CustChasFinance', 'app_CustFinanInterest', 'app_CustEMI',
       'app_CustTotInflow', 'Label', 'Score', 'AnotherScore'],
      dtype='object')

In [13]:
cibil.columns[7:9]

Index(['Score', 'AnotherScore'], dtype='object')

In [10]:
cnt = 0
for i in range(len(commercial['cus_CustomerCode'])):
    for j in range(len(cibil['CustomerCode'])):
        if commercial['cus_CustomerCode'][i] == cibil['CustomerCode'][j]:
            print('Yes')
            cnt = cnt+1
            print(cnt)

Yes
1
Yes
2
Yes
3
Yes
4
Yes
5
Yes
6
Yes
7
Yes
8
Yes
9
Yes
10
Yes
11
Yes
12
Yes
13
Yes
14
Yes
15
Yes
16
Yes
17
Yes
18
Yes
19
Yes
20
Yes
21
Yes
22
Yes
23
Yes
24
Yes
25
Yes
26
Yes
27
Yes
28
Yes
29
Yes
30
Yes
31
Yes
32
Yes
33
Yes
34
Yes
35
Yes
36
Yes
37
Yes
38
Yes
39
Yes
40
Yes
41
Yes
42
Yes
43
Yes
44
Yes
45
Yes
46
Yes
47
Yes
48
Yes
49
Yes
50
Yes
51
Yes
52
Yes
53
Yes
54
Yes
55
Yes
56
Yes
57
Yes
58
Yes
59
Yes
60
Yes
61
Yes
62
Yes
63
Yes
64
Yes
65
Yes
66
Yes
67
Yes
68
Yes
69
Yes
70
Yes
71
Yes
72
Yes
73
Yes
74
Yes
75
Yes
76
Yes
77
Yes
78
Yes
79
Yes
80
Yes
81
Yes
82
Yes
83
Yes
84
Yes
85
Yes
86
Yes
87
Yes
88
Yes
89
Yes
90
Yes
91
Yes
92
Yes
93
Yes
94
Yes
95
Yes
96
Yes
97
Yes
98
Yes
99
Yes
100
Yes
101
Yes
102
Yes
103
Yes
104
Yes
105
Yes
106
Yes
107
Yes
108
Yes
109
Yes
110
Yes
111
Yes
112
Yes
113
Yes
114
Yes
115
Yes
116
Yes
117
Yes
118
Yes
119
Yes
120
Yes
121
Yes
122
Yes
123
Yes
124
Yes
125
Yes
126
Yes
127
Yes
128
Yes
129
Yes
130
Yes
131
Yes
132
Yes
133
Yes
134
Yes
135
Yes
136
Yes
137
Yes
138
Yes
139
Yes
140
Yes
141
Yes
142
Yes
143
Yes
144
Yes
145
Yes
146
Yes
147
Yes
148
Yes
149
Yes
150
Yes
151
Yes
152
Yes
153
Yes
154
Yes
155
Yes
156
Yes
157
Yes
158
Yes
159
Yes
160
Yes
161
Yes
162
Yes
163
Yes
164
Yes
165
Yes
166
Yes
167
Yes
168
Yes
169
Yes
170
Yes
171
Yes
172
Yes
173
Yes
174
Yes
175
Yes
176
Yes
177
Yes
178
Yes
179
Yes
180
Yes
181
Yes
182
Yes
183
Yes
184
Yes
185
Yes
186
Yes
187
Yes
188
Yes
189
Yes
190
Yes
191
Yes
192
Yes
193
Yes
194
Yes
195
Yes
196
Yes
197
Yes
198
Yes
199
Yes
200
Yes
201
Yes
202
Yes
203
Yes
204
Yes
205
Yes
206
Yes
207
Yes
208
Yes
209
Yes
210
Yes
211
Yes
212
Yes
213
Yes
214
Yes
215
Yes
216
Yes
217
Yes
218
Yes
219
Yes
220
Yes
221
Yes
222
Yes
223
Yes
224
Yes
225
Yes
226
Yes
227
Yes
228
Yes
229
Yes
230
Yes
231
Yes
232
Yes
233
Yes
234
Yes
235
Yes
236
Yes
237
Yes
238
Yes
239
Yes
240
Yes
241
Yes
242
Yes
243
Yes
244
Yes
245
Yes
246
Yes
247
Yes
248
Yes
249
Yes
250
Yes
251
Yes
252
Yes
253
Yes
254
Yes
255
Yes
256
Yes
257
Yes
258
Yes
259
Yes
260
Yes
261
Yes
262
Yes
263
Yes
264
Yes
265
Yes
266
Yes
267
Yes
268
Yes
269
Yes
270
Yes
271
Yes
272
Yes
273
Yes
274
Yes
275
Yes
276
Yes
277
Yes
278
Yes
279
Yes
280
Yes
281
Yes
282
Yes
283
Yes
284
Yes
285
Yes
286
Yes
287
Yes
288
Yes
289
Yes
290
Yes
291
Yes
292
Yes
293
Yes
294
Yes
295
Yes
296
Yes
297
Yes
298
Yes
299
Yes
300
Yes
301
Yes
302
Yes
303
Yes
304
Yes
305
Yes
306
Yes
307
Yes
308
Yes
309
Yes
310
Yes
311
Yes
312
Yes
313
Yes
314
Yes
315
Yes
316
Yes
317
Yes
318
Yes
319
Yes
320
Yes
321
Yes
322
Yes
323
Yes
324
Yes
325
Yes
326
Yes
327
Yes
328
Yes
329
Yes
330
Yes
331
Yes
332
Yes
333
Yes
334
Yes
335
Yes
336
Yes
337
Yes
338
Yes
339
Yes
340
Yes
341
Yes
342
Yes
343
Yes
344
Yes
345
Yes
346
Yes
347
Yes
348
Yes
349
Yes
350
Yes
351
Yes
352
Yes
353
Yes
354
Yes
355
Yes
356
Yes
357
Yes
358
Yes
359
Yes
360
Yes
361
Yes
362
Yes
363
Yes
364
Yes
365
Yes
366
Yes
367
Yes
368
Yes
369
Yes
370
Yes
371
Yes
372
Yes
373
Yes
374
Yes
375
Yes
376
Yes
377
Yes
378
Yes
379
Yes
380
Yes
381
Yes
382
Yes
383
Yes
384
Yes
385
Yes
386
Yes
387
Yes
388
Yes
389
Yes
390
Yes
391
Yes
392
Yes
393
Yes
394
Yes
395
Yes
396
Yes
397
Yes
398
Yes
399
Yes
400
Yes
401
Yes
402
Yes
403
Yes
404
Yes
405
Yes
406
Yes
407
Yes
408
Yes
409
Yes
410
Yes
411
Yes
412
Yes
413
Yes
414
Yes
415
Yes
416
Yes
417
Yes
418
Yes
419
Yes
420
Yes
421
Yes
422
Yes
423
Yes
424
Yes
425
Yes
426
Yes
427
Yes
428
Yes
429
Yes
430
Yes
431
Yes
432
Yes
433
Yes
434
Yes
435
Yes
436
Yes
437
Yes
438
Yes
439
Yes
440
Yes
441
Yes
442
Yes
443
Yes
444
Yes
445
Yes
446
Yes
447
Yes
448
Yes
449
Yes
450
Yes
451
Yes
452
Yes
453
Yes
454
Yes
455
Yes
456
Yes
457
Yes
458
Yes
459
Yes
460
Yes
461
Yes
462
Yes
463
Yes
464
Yes
465
Yes
466
Yes
467
Yes
468
Yes
469
Yes
470
Yes
471
Yes
472
Yes
473
Yes
474
Yes
475
Yes
476
Yes
477
Yes
478
Yes
479
Yes
480
Yes
481
Yes
482
Yes
483
Yes
484
Yes
485
Yes
486
Yes
487
Yes
488
Yes
489
Yes
490
Yes
491
Yes
492
Yes
493
Yes
494
Yes
495
Yes
496
Yes
497
Yes
498
Yes
499
Yes
500
Yes
501
Yes
502
Yes
503
Yes
504
Yes
505
Yes
506
Yes
507
Yes
508
Yes
509
Yes
510
Yes
511
Yes
512
Yes
513
Yes
514
Yes
515
Yes
516
Yes
517
Yes
518
Yes
519
Yes
520
Yes
521
Yes
522
Yes
523
Yes
524
Yes
525
Yes
526
Yes
527
Yes
528
Yes
529
Yes
530
Yes
531
Yes
532
Yes
533
Yes
534
Yes
535
Yes
536
Yes
537
Yes
538
Yes
539
Yes
540
Yes
541
Yes
542
Yes
543
Yes
544
Yes
545
Yes
546
Yes
547
Yes
548
Yes
549
Yes
550
Yes
551
Yes
552
Yes
553
Yes
554
Yes
555
Yes
556
Yes
557
Yes
558
Yes
559
Yes
560
Yes
561
Yes
562
Yes
563
Yes
564
Yes
565
Yes
566
Yes
567
Yes
568
Yes
569
Yes
570
Yes
571
Yes
572
Yes
573
Yes
574
Yes
575
Yes
576
Yes
577
Yes
578
Yes
579
Yes
580
Yes
581
Yes
582
Yes
583
Yes
584
Yes
585
Yes
586
Yes
587
Yes
588
Yes
589
Yes
590
Yes
591
Yes
592
Yes
593
Yes
594
Yes
595
Yes
596
Yes
597
Yes
598
Yes
599
Yes
600
Yes
601
Yes
602
Yes
603
Yes
604
Yes
605
Yes
606
Yes
607
Yes
608
Yes
609
Yes
610
Yes
611
Yes
612
Yes
613
Yes
614
Yes
615
Yes
616
Yes
617
Yes
618
Yes
619
Yes
620
Yes
621
Yes
622
Yes
623
Yes
624
Yes
625
Yes
626
Yes
627
Yes
628
Yes
629
Yes
630
Yes
631
Yes
632
Yes
633
Yes
634
Yes
635
Yes
636
Yes
637
Yes
638
Yes
639
Yes
640
Yes
641
Yes
642
Yes
643
Yes
644
Yes
645
Yes
646
Yes
647
Yes
648
Yes
649
Yes
650
Yes
651
Yes
652
Yes
653
Yes
654
Yes
655
Yes
656
Yes
657
Yes
658
Yes
659
Yes
660
Yes
661
Yes
662
Yes
663
Yes
664
Yes
665
Yes
666
Yes
667
Yes
668
Yes
669
Yes
670
Yes
671
Yes
672
Yes
673
Yes
674
Yes
675
Yes
676
Yes
677
Yes
678
Yes
679
Yes
680
Yes
681
Yes
682
Yes
683
Yes
684
Yes
685
Yes
686
Yes
687
Yes
688
Yes
689
Yes
690
Yes
691
Yes
692
Yes
693
Yes
694
Yes
695
Yes
696
Yes
697
Yes
698
Yes
699
Yes
700
Yes
701
Yes
702
Yes
703
Yes
704
Yes
705
Yes
706
Yes
707
Yes
708
Yes
709
Yes
710
Yes
711
Yes
712
Yes
713
Yes
714
Yes
715
Yes
716
Yes
717
Yes
718
Yes
719
Yes
720
Yes
721
Yes
722
Yes
723
Yes
724
Yes
725
Yes
726
Yes
727
Yes
728
Yes
729
Yes
730
Yes
731
Yes
732
Yes
733
Yes
734
Yes
735
Yes
736
Yes
737
Yes
738
Yes
739
Yes
740
Yes
741
Yes
742
Yes
743
Yes
744
Yes
745
Yes
746
Yes
747
Yes
748
Yes
749
Yes
750
Yes
751
Yes
752
Yes
753
Yes
754
Yes
755
Yes
756
Yes
757
Yes
758
Yes
759
Yes
760
Yes
761
Yes
762
Yes
763
Yes
764
Yes
765
Yes
766
Yes
767
Yes
768
Yes
769
Yes
770
Yes
771
Yes
772
Yes
773
Yes
774
Yes
775
Yes
776
Yes
777
Yes
778
Yes
779
Yes
780
Yes
781
Yes
782
Yes
783
Yes
784
Yes
785
Yes
786
Yes
787
Yes
788
Yes
789
Yes
790
Yes
791
Yes
792
Yes
793
Yes
794
Yes
795
Yes
796
Yes
797
Yes
798
Yes
799
Yes
800
Yes
801
Yes
802
Yes
803
Yes
804
Yes
805
Yes
806
Yes
807
Yes
808
Yes
809
Yes
810
Yes
811
Yes
812
Yes
813
Yes
814
Yes
815
Yes
816
Yes
817
Yes
818
Yes
819
Yes
820
Yes
821
Yes
822
Yes
823
Yes
824
Yes
825
Yes
826
Yes
827
Yes
828
Yes
829
Yes
830
Yes
831
Yes
832
Yes
833
Yes
834
Yes
835
Yes
836
Yes
837
Yes
838
Yes
839
Yes
840
Yes
841
Yes
842
Yes
843
Yes
844
Yes
845
Yes
846
Yes
847
Yes
848
Yes
849
Yes
850
Yes
851
Yes
852
Yes
853
Yes
854
Yes
855
Yes
856
Yes
857
Yes
858
Yes
859
Yes
860
Yes
861
Yes
862
Yes
863
Yes
864
Yes
865
Yes
866
Yes
867
Yes
868
Yes
869
Yes
870
Yes
871
Yes
872
Yes
873
Yes
874
Yes
875
Yes
876
Yes
877
Yes
878
Yes
879
Yes
880
Yes
881
Yes
882
Yes
883
Yes
884
Yes
885
Yes
886
Yes
887
Yes
888
Yes
889
Yes
890
Yes
891
Yes
892
Yes
893
Yes
894
Yes
895
Yes
896
Yes
897
Yes
898
Yes
899
Yes
900

In [14]:
#Appending Scores with corresponding user:
for i in range(len(commercial['cus_CustomerCode'])):
    for j in range(len(cibil['CustomerCode'])):
        if commercial['cus_CustomerCode'][i] == cibil['CustomerCode'][j]:
            commer = commercial.iloc[i].values.tolist()
            commer[-2:] = cibil.iloc[j].values.tolist()[7:9]
            commercial.iloc[i] = commer

In [15]:
commercial.shape

(600, 23)

In [16]:
print(commercial.AnotherScore.isnull().sum())
print(commercial.Score.isnull().sum())

140
140

In [17]:
null_records = commercial.shape[0] - commercial.AnotherScore.isnull().sum()
print("Their is a {} Records with cibil are found..".format(null_records))

Their is a 460 Records with cibil are found..

In [18]:
#Pre-processing Cibil Score:
def cibil(x):
    if x == '000-1':
        return 1
    else:
        return x

In [19]:
commercial.Score = commercial.Score.apply(cibil)

In [20]:
commercial.Score.value_counts()

1.0      339
2.0        7
3.0        6
710.0      4
706.0      4
        ...
750.0      1
740.0      1
548.0      1
590.0      1
721.0      1
Name: Score, Length: 86, dtype: int64

In [21]:
for i in commercial.columns:
    print(commercial[i].value_counts())

APTW007146    2
APTW068546    1
APTW115169    1
APTW010991    1
APTW048325    1
             ..
APTW180861    1
APTW069596    1
APTW150683    1
ATTW154548    1
APTW038227    1
Name: cus_CustomerCode, Length: 599, dtype: int64
M    502
F     98
Name: cus_Gender, dtype: int64
1985-01-01    9
1994-01-01    8
1991-01-01    7
1983-01-01    7
1990-01-01    7
             ..
1996-06-08    1
1970-08-22    1
1992-09-02    1
1987-10-07    1
1979-04-22    1
Name: cus_DOB, Length: 498, dtype: int64
1900-01-02    447
1900-01-01    153
Name: cus_MartialTypeId, dtype: int64
0    411
2     70
3     41
4     40
1     27
5      8
9      1
8      1
6      1
Name: cus_Dependants, dtype: int64
1    512
2     88
Name: cus_CurrenResTypeId, dtype: int64
20    85
10    84
15    45
30    36
5     31
25    30
14    29
2     27
6     16
35    16
33    15
40    15
3     14
23    11
8     10
22    10
9      9
29     9
27     8
21     7
24     7
19     7
1      6
18     6
32     6
12     6
7      6
26     5
17     3
0      3
39     3
31     3
44     3
43     3
42     3
28     2
46     2
4      2
50     2
37     2
36     2
13     2
34     2
16     2
56     2
38     1
45     1
49     1
Name: cus_CurrenStyYear, dtype: int64
0        376
1000      61
1500      29
5000      22
2000      15
2500      13
6500       9
1200       9
1100       7
10000      7
3000       4
4500       3
500        3
6000       3
4000       3
5500       2
15200      2
3289       1
5349       1
12500      1
5246       1
200        1
12458      1
5279       1
8463       1
6249       1
100        1
5200       1
18500      1
15400      1
8437       1
5106       1
13625      1
4673       1
25561      1
15222      1
8045       1
3816       1
6819       1
7829       1
1598       1
2400       1
63000      1
5642       1
4592       1
4562       1
25000      1
1400       1
3500       1
Name: app_CustBankClosBal, dtype: int64
0          534
265000      16
250000      11
200000      11
150000       6
245000       5
300000       3
268000       2
285000       2
254000       2
650000       1
1250000      1
320000       1
215000       1
2500000      1
154000       1
1500000      1
1200000      1
Name: app_CustAssetValue, dtype: int64
1541    600
Name: app_CustProductCatTypeId, dtype: int64
1360    231
1542    216
935      37
1544     37
816      28
1547     20
1546     14
1647      8
1549      6
1734      1
1545      1
1476      1
Name: app_CustBrandTypeId, dtype: int64
1783    281
879     140
1782     74
603      46
877      43
878       5
605       5
875       2
658       2
604       2
Name: app_CustIndustryTypeId, dtype: int64
24    375
18    113
30     51
12     40
36     15
31      1
25      1
23      1
21      1
20      1
19      1
Name: app_CustTenure, dtype: int64
24    286
18     94
23     84
30     33
12     26
17     19
29     16
11     10
36      9
22      7
35      5
10      3
28      2
21      1
20      1
27      1
16      1
34      1
9       1
Name: app_CustInstalCount, dtype: int64
56823     9
66000     6
73500     6
62000     6
63500     6
         ..
78500     1
57000     1
75500     1
69293     1
194560    1
Name: app_CustChasAsset, Length: 450, dtype: int64
13000    8
10000    7
14000    6
11000    6
10500    5
        ..
19100    1
18452    1
12478    1
19110    1
30200    1
Name: app_CustChasInitial, Length: 471, dtype: int64
45000     20
50000     17
42000     17
40000     17
53000     16
          ..
43625      1
145000     1
38500      1
63070      1
70600      1
Name: app_CustChasFinance, Length: 207, dtype: int64
13.00    151
12.50     69
12.00     59
13.50     54
11.75     45
        ...
12.60      1
12.91      1
11.34      1
11.19      1
12.53      1
Name: app_CustFinanInterest, Length: 64, dtype: int64
2835    8
2783    7
2730    7
3413    5
2672    5
       ..
2722    1
1705    1
3531    1
1710    1
5120    1
Name: app_CustEMI, Length: 445, dtype: int64
2000    110
1800    105
2300     79
1500     64
2500     43
1300     39
1200     30
2800     26
0        22
1000     18
500       8
1700      8
2100      5
2700      5
3300      4
3400      4
2200      3
3000      3
700       2
3200      2
4300      1
2060      1
2080      1
2600      1
2160      1
1202      1
2240      1
200       1
3591      1
4600      1
750       1
3335      1
3651      1
1400      1
3450      1
5577      1
2520      1
550       1
2580      1
3800      1
Name: app_CustTotInflow, dtype: int64
Not Pay    400
Pay        200
Name: Label, dtype: int64
1.0      339
2.0        7
3.0        6
710.0      4
706.0      4
        ...
750.0      1
740.0      1
548.0      1
590.0      1
721.0      1
Name: Score, Length: 86, dtype: int64
888    117
884    115
907     38
923     35
909     15
959     13
960     11
887     10
883      9
904      8
838      5
967      5
925      5
951      5
934      4
832      4
903      4
900      4
920      3
906      3
864      3
665      2
938      2
940      2
891      2
968      2
974      2
981      2
863      2
932      2
912      1
966      1
905      1
796      1
899      1
928      1
667      1
807      1
924      1
889      1
880      1
995      1
983      1
979      1
973      1
965      1
957      1
809      1
954      1
947      1
818      1
890      1
687      1
942      1
939      1
763      1
Name: AnotherScore, dtype: int64

In [22]:
#Removing '-' from dataset:
for i in commercial.columns:
    commercial[i][commercial[i] == '-'] = np.nan

C:\Users\ESFITA-USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ESFITA-USER\Anaconda3\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

In [23]:
commercial.head()

,cus_CustomerCode,cus_Gender,cus_DOB,cus_MartialTypeId,cus_Dependants,cus_CurrenResTypeId,cus_CurrenStyYear,app_CustBankClosBal,app_CustAssetValue,app_CustProductCatTypeId,...,app_CustInstalCount,app_CustChasAsset,app_CustChasInitial,app_CustChasFinance,app_CustFinanInterest,app_CustEMI,app_CustTotInflow,Label,Score,AnotherScore
0,APTW058710,M,1971-04-09,1900-01-02,0,1,15,3289,0,1541,...,24,63397,21397,42000,13.50,2223,1800,Pay,1.0,907
1,APTW058587,M,1994-02-15,1900-01-02,2,1,14,4562,0,1541,...,18,63000,22000,41000,13.00,2722,1800,Pay,1.0,884
2,APTW058718,M,1974-09-03,1900-01-02,2,1,16,5246,0,1541,...,18,53747,22747,31000,10.03,1981,1800,Pay,1.0,907
3,APTW057714,M,1985-05-07,1900-01-01,4,1,28,6249,0,1541,...,24,61011,19011,42000,10.50,2118,1800,Pay,1.0,888
4,APTW060335,M,1970-03-02,1900-01-02,3,1,14,4673,0,1541,...,24,54247,18247,36000,13.50,1905,1800,Pay,1.0,907

In [24]:
print(commercial.columns)
print(commercial.isnull().sum())

Index(['cus_CustomerCode', 'cus_Gender', 'cus_DOB', 'cus_MartialTypeId',
       'cus_Dependants', 'cus_CurrenResTypeId', 'cus_CurrenStyYear',
       'app_CustBankClosBal', 'app_CustAssetValue', 'app_CustProductCatTypeId',
       'app_CustBrandTypeId', 'app_CustIndustryTypeId', 'app_CustTenure',
       'app_CustInstalCount', 'app_CustChasAsset', 'app_CustChasInitial',
       'app_CustChasFinance', 'app_CustFinanInterest', 'app_CustEMI',
       'app_CustTotInflow', 'Label', 'Score', 'AnotherScore'],
      dtype='object')
cus_CustomerCode              0
cus_Gender                    0
cus_DOB                       0
cus_MartialTypeId             0
cus_Dependants                0
cus_CurrenResTypeId           0
cus_CurrenStyYear             0
app_CustBankClosBal           0
app_CustAssetValue            0
app_CustProductCatTypeId      0
app_CustBrandTypeId           0
app_CustIndustryTypeId        0
app_CustTenure                0
app_CustInstalCount           0
app_CustChasAsset             0
app_CustChasInitial           0
app_CustChasFinance           0
app_CustFinanInterest         0
app_CustEMI                   0
app_CustTotInflow             0
Label                         0
Score                       140
AnotherScore                140
dtype: int64

### Feature Handling:

In [25]:
commercial.cus_MartialTypeId.value_counts()

1900-01-02    447
1900-01-01    153
Name: cus_MartialTypeId, dtype: int64

In [26]:
def mar(x):
    """
    Method to handle MarialTypeId Feature.
    """
    if x == 2:
        return 2751
    else:
        return 2750

In [27]:
commercial.cus_MartialTypeId = commercial.cus_MartialTypeId.apply(mar)

In [28]:
commercial.cus_MartialTypeId.value_counts()

2750    600
Name: cus_MartialTypeId, dtype: int64

In [29]:
commercial.shape

(600, 23)

In [30]:
commercial.cus_MartialTypeId.fillna(commercial.cus_MartialTypeId.value_counts().index[0],inplace=True)

In [31]:
commercial.cus_MartialTypeId.value_counts()

2750    600
Name: cus_MartialTypeId, dtype: int64

In [32]:
commercial.cus_Gender.value_counts()

M    502
F     98
Name: cus_Gender, dtype: int64

In [33]:
def gen(x):
    """
    Method to handle MarialTypeId Feature.
    """
    if x == " ":
        return np.nan
    if x == 1:
        return "M"
    else:
        return x

In [34]:
commercial.cus_Gender = commercial.cus_Gender.apply(gen)

In [35]:
commercial.cus_Gender.fillna(commercial.cus_Gender.value_counts().index[0],inplace=True)

In [36]:
commercial.cus_Gender.value_counts()

M    502
F     98
Name: cus_Gender, dtype: int64

In [38]:
commercial.cus_CurrenResTypeId.value_counts()

1    512
2     88
Name: cus_CurrenResTypeId, dtype: int64

In [39]:
def res_type(x):
    """
    Method to handle ResiTypeId Feature.
    """
    if x == 1:
        return 2755
    if x == 2:
        return 2756
    else:
        return x

In [40]:
commercial.cus_CurrenResTypeId = commercial.cus_CurrenResTypeId.apply(res_type)

In [41]:
commercial.cus_CurrenResTypeId.fillna(commercial.cus_CurrenResTypeId.value_counts().index[0],inplace=True)

In [42]:
commercial.cus_CurrenResTypeId.value_counts()

2755    512
2756     88
Name: cus_CurrenResTypeId, dtype: int64

In [44]:
commercial.app_CustIndustryTypeId.value_counts()

1783    281
879     140
1782     74
603      46
877      43
878       5
605       5
875       2
658       2
604       2
Name: app_CustIndustryTypeId, dtype: int64

In [45]:
commercial.app_CustIndustryTypeId.fillna(commercial.app_CustIndustryTypeId.value_counts().index[0],inplace=True)

In [47]:
commercial.app_CustIndustryTypeId.value_counts()

1783    281
879     140
1782     74
603      46
877      43
878       5
605       5
875       2
658       2
604       2
Name: app_CustIndustryTypeId, dtype: int64

In [48]:
commercial.app_CustProductCatTypeId.value_counts()

1541    600
Name: app_CustProductCatTypeId, dtype: int64

In [49]:
commercial.app_CustProductCatTypeId.fillna(commercial.app_CustProductCatTypeId.value_counts().index[0],inplace=True)

In [50]:
commercial.app_CustProductCatTypeId.value_counts()

1541    600
Name: app_CustProductCatTypeId, dtype: int64

In [51]:
commercial.app_CustBrandTypeId.value_counts()

1360    231
1542    216
935      37
1544     37
816      28
1547     20
1546     14
1647      8
1549      6
1734      1
1545      1
1476      1
Name: app_CustBrandTypeId, dtype: int64

In [52]:
commercial.app_CustBrandTypeId.fillna(commercial.app_CustBrandTypeId.value_counts().index[0],inplace=True)

In [53]:
commercial.isnull().sum()

cus_CustomerCode              0
cus_Gender                    0
cus_DOB                       0
cus_MartialTypeId             0
cus_Dependants                0
cus_CurrenResTypeId           0
cus_CurrenStyYear             0
app_CustBankClosBal           0
app_CustAssetValue            0
app_CustProductCatTypeId      0
app_CustBrandTypeId           0
app_CustIndustryTypeId        0
app_CustTenure                0
app_CustInstalCount           0
app_CustChasAsset             0
app_CustChasInitial           0
app_CustChasFinance           0
app_CustFinanInterest         0
app_CustEMI                   0
app_CustTotInflow             0
Label                         0
Score                       140
AnotherScore                140
dtype: int64

In [82]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_DOB', 'cus_MartialTypeId',
       'cus_Dependants', 'cus_CurrenResTypeId', 'cus_CurrenStyYear',
       'app_CustBankClosBal', 'app_CustAssetValue', 'app_CustProductCatTypeId',
       'app_CustBrandTypeId', 'app_CustIndustryTypeId', 'app_CustTenure',
       'app_CustInstalCount', 'app_CustChasAsset', 'app_CustChasInitial',
       'app_CustChasFinance', 'app_CustFinanInterest', 'app_CustEMI',
       'app_CustTotInflow', 'Label', 'Score', 'AnotherScore'],
      dtype='object')

In [85]:
def dob(x):
    year = str(x).split('-')[0]
    curr_year = 2020
    return (curr_year-int(year))

In [88]:
commercial['cus_Age'] = commercial.cus_DOB.apply(dob)

In [90]:
commercial.drop('cus_DOB',axis=1,inplace=True)

In [91]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_MartialTypeId', 'cus_Dependants',
       'cus_CurrenResTypeId', 'cus_CurrenStyYear', 'app_CustBankClosBal',
       'app_CustAssetValue', 'app_CustProductCatTypeId', 'app_CustBrandTypeId',
       'app_CustIndustryTypeId', 'app_CustTenure', 'app_CustInstalCount',
       'app_CustChasAsset', 'app_CustChasInitial', 'app_CustChasFinance',
       'app_CustFinanInterest', 'app_CustEMI', 'app_CustTotInflow', 'Label',
       'Score', 'AnotherScore', 'cus_Age'],
      dtype='object')

In [101]:
loan_to_value = []
frame = commercial[['app_CustChasAsset','app_CustChasFinance']]
loan = (frame.app_CustChasFinance*100/frame.app_CustChasAsset)

In [102]:
for i in loan:
    if (i<85):
        loan_to_value.append(120)
    elif ((i>=85) and (i <=90)):
        loan_to_value.append(100)
    elif (i>90):
        loan_to_value.append(50)

In [103]:
commercial["Loan_to_Value"] = loan_to_value

In [107]:
asset_finance = []
frame = commercial.app_CustBrandTypeId

In [110]:
for i in frame:
    # Approved Models (Hero /Honda/Suzuki  - All Products)
    if ((i == 1360) | (i == 1542) | (i == 1544) | (i == 1546)):
        asset_finance.append(100)
    
    # Unapproved Models (Only Yahama, TVS and Royal Enfield Bike Variants) with PM Approval:
    elif ((i == 1547) | (i == 1647) | (i == 935) | (i == 1549)):  
        asset_finance.append(50)
    
    else:
        asset_finance.append(-100)

In [113]:
commercial["Asset_Financed"] = asset_finance

In [116]:
gi = []
frame = commercial.app_CustTotInflow*12

In [118]:
for i in frame:
    if i > 12000:
        gi.append(100)
    elif i>8000 and i<=12000:
        gi.append(70)
    elif i >= 5000 and i<=8000:
        gi.append(50)
    elif i < 5000:
        gi.append(-50)

In [121]:
commercial["Gross Income"] = gi

In [122]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_MartialTypeId', 'cus_Dependants',
       'cus_CurrenResTypeId', 'cus_CurrenStyYear', 'app_CustBankClosBal',
       'app_CustAssetValue', 'app_CustProductCatTypeId', 'app_CustBrandTypeId',
       'app_CustIndustryTypeId', 'app_CustTenure', 'app_CustInstalCount',
       'app_CustChasAsset', 'app_CustChasInitial', 'app_CustChasFinance',
       'app_CustFinanInterest', 'app_CustEMI', 'app_CustTotInflow', 'Label',
       'Score', 'AnotherScore', 'cus_Age', 'Loan_to_Value', 'Asset_Financed',
       'Gross Income'],
      dtype='object')

In [125]:
frame = commercial[['app_CustEMI','app_CustBankClosBal','cus_CurrenResTypeId', 'cus_CurrenStyYear','AnotherScore']]
list1 = frame.values.tolist()

In [138]:
banking = []
for i in list1:
    if ((i[0]>i[1]) and (i[2] == 2756 and i[3]>3)):
        banking.append(100)
    elif ((i[0]>i[1]) and (i[2] == 2755)):
        banking.append(100)
    elif ((i[0]>i[1]) and (i[2] == 2756 and i[3]>2)):
        banking.append(80)
    elif ((i[0]<i[1]) or (i[2] == 2756 and i[3]<2)):
        banking.append(-100)
    elif i[4]>600:
        banking.append(100)

In [140]:
len(banking)

600

In [142]:
commercial["Banking"] = banking

In [149]:
stabiltiy = []
for i in range(commercial.shape[0]):
        stabiltiy.append(int(np.random.choice([100,80,-80],1)))

In [150]:
len(stabiltiy)

600

In [151]:
commercial["Employment_Stabilty"] = stabiltiy

In [156]:
frame = commercial[['cus_Age','cus_MartialTypeId', 'cus_Dependants']]
list1 = frame.values.tolist()

In [176]:
age = []
for i in list1:
    #Age between 21 and 50 years, Married with No Dependents
    if ((i[0]>=21 and i[0]<=50) and (i[1]==2750 and i[2] == 0)):
        age.append(120)
        
    #Age between 21 and 50 years, Married with Dependents
    elif ((i[0]>=21 and i[0]<=50) and (i[1]==2750 and i[2] != 0)):
        age.append(100)
        
    #Age between 51 and 62 years, Married with Dependents
    elif ((i[0]>=51 and i[0]<=62) and (i[1]==2750 and i[2] == 0)):
        age.append(80)
        
    #Age between 51 and 62 years, Married with Dependents
    elif ((i[0]>=51 and i[0]<=62) and (i[1]==2750 and i[2] != 0)):
        age.append(60)
        
    #Age between 21 and 40 years, Married with Dependents
    elif ((i[0]>=21 and i[0]<=40) and (i[1]==2751)):
        age.append(100)
        
    else:
        age.append(0)

In [177]:
len(age)

600

In [178]:
commercial["Age_Martial"] = age

In [182]:
commercial = commercial[['cus_CustomerCode', 'cus_Gender', 'cus_MartialTypeId', 'cus_Dependants',
       'cus_CurrenResTypeId', 'cus_CurrenStyYear', 'app_CustBankClosBal',
       'app_CustAssetValue', 'app_CustProductCatTypeId', 'app_CustBrandTypeId',
       'app_CustIndustryTypeId', 'app_CustTenure', 'app_CustInstalCount',
       'app_CustChasAsset', 'app_CustChasInitial', 'app_CustChasFinance',
       'app_CustFinanInterest', 'app_CustEMI', 'app_CustTotInflow',
       'Score', 'AnotherScore', 'cus_Age', 'Loan_to_Value', 'Asset_Financed',
       'Gross Income', 'Banking', 'Employment_Stabilty', 'Age_Martial', 'Label']]

In [183]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_MartialTypeId', 'cus_Dependants',
       'cus_CurrenResTypeId', 'cus_CurrenStyYear', 'app_CustBankClosBal',
       'app_CustAssetValue', 'app_CustProductCatTypeId', 'app_CustBrandTypeId',
       'app_CustIndustryTypeId', 'app_CustTenure', 'app_CustInstalCount',
       'app_CustChasAsset', 'app_CustChasInitial', 'app_CustChasFinance',
       'app_CustFinanInterest', 'app_CustEMI', 'app_CustTotInflow', 'Score',
       'AnotherScore', 'cus_Age', 'Loan_to_Value', 'Asset_Financed',
       'Gross Income', 'Banking', 'Employment_Stabilty', 'Age_Martial',
       'Label'],
      dtype='object')

In [187]:
commercial['Geo_Limit'] = [int(np.random.choice([0,1],1)) for i in range(commercial.shape[0])]

C:\Users\ESFITA-USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [188]:
commercial

,cus_CustomerCode,cus_Gender,cus_MartialTypeId,cus_Dependants,cus_CurrenResTypeId,cus_CurrenStyYear,app_CustBankClosBal,app_CustAssetValue,app_CustProductCatTypeId,app_CustBrandTypeId,...,AnotherScore,cus_Age,Loan_to_Value,Asset_Financed,Gross Income,Banking,Employment_Stabilty,Age_Martial,Label,Geo_Limit
0,APTW058710,M,2750,0,2755,15,3289,0,1541,1360,...,907,49,120,100,100,-100,80,120,Pay,0
1,APTW058587,M,2750,2,2755,14,4562,0,1541,1542,...,884,26,120,100,100,-100,100,100,Pay,0
2,APTW058718,M,2750,2,2755,16,5246,0,1541,1542,...,907,46,120,100,100,-100,80,100,Pay,0
3,APTW057714,M,2750,4,2755,28,6249,0,1541,1360,...,888,35,120,100,100,-100,100,100,Pay,0
4,APTW060335,M,2750,3,2755,14,4673,0,1541,1542,...,907,50,120,100,100,-100,-80,100,Pay,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,APTW049489,M,2750,2,2755,20,0,0,1541,1546,...,NaN,41,120,100,100,100,80,100,Not Pay,1
596,APTW022896,M,2750,0,2755,22,0,0,1541,1544,...,NaN,29,120,100,100,100,80,120,Not Pay,0
597,APTW048649,M,2750,0,2755,10,0,0,1541,1542,...,NaN,44,120,100,100,100,80,120,Not Pay,1
598,APTW048908,M,2750,0,2755,2,2000,0,1541,816,...,NaN,45,120,-100,100,100,80,120,Not Pay,1
599,APTW014729,M,2750,1,2755,30,0,0,1541,935,...,NaN,56,120,50,100,100,-80,60,Not Pay,0

In [190]:
commercial = commercial[['cus_CustomerCode', 'cus_Gender', 'cus_MartialTypeId', 'cus_Dependants',
       'cus_CurrenResTypeId', 'cus_CurrenStyYear', 'app_CustBankClosBal',
       'app_CustAssetValue', 'app_CustProductCatTypeId', 'app_CustBrandTypeId',
       'app_CustIndustryTypeId', 'app_CustTenure', 'app_CustInstalCount',
       'app_CustChasAsset', 'app_CustChasInitial', 'app_CustChasFinance',
       'app_CustFinanInterest', 'app_CustEMI', 'app_CustTotInflow', 'Score',
       'AnotherScore', 'cus_Age', 'Loan_to_Value', 'Asset_Financed',
       'Gross Income', 'Banking', 'Employment_Stabilty', 'Age_Martial',
       'Geo_Limit','Label']]

In [192]:
commercial.columns

Index(['cus_CustomerCode', 'cus_Gender', 'cus_MartialTypeId', 'cus_Dependants',
       'cus_CurrenResTypeId', 'cus_CurrenStyYear', 'app_CustBankClosBal',
       'app_CustAssetValue', 'app_CustProductCatTypeId', 'app_CustBrandTypeId',
       'app_CustIndustryTypeId', 'app_CustTenure', 'app_CustInstalCount',
       'app_CustChasAsset', 'app_CustChasInitial', 'app_CustChasFinance',
       'app_CustFinanInterest', 'app_CustEMI', 'app_CustTotInflow', 'Score',
       'AnotherScore', 'cus_Age', 'Loan_to_Value', 'Asset_Financed',
       'Gross Income', 'Banking', 'Employment_Stabilty', 'Age_Martial',
       'Geo_Limit', 'Label'],
      dtype='object')

In [193]:
commercial.to_csv('Train_Data_TW.csv',index=False)